# Generated by Django 5.1.3 on 2024-12-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_plane_seat_flight_alter_seat_seat_class'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked_ticket', to='flights.seat'),
        ),
    ]
