# Generated by Django 5.1.4 on 2024-12-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='information',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
    ]
