# Generated by Django 5.1.4 on 2024-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_announcement_tag_remove_discount_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
