# Generated by Django 5.1.4 on 2024-12-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
