# Generated by Django 5.1.3 on 2024-12-03 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('first_class_capacity', models.IntegerField()),
                ('business_class_capacity', models.IntegerField()),
                ('premium_class_capacity', models.IntegerField()),
                ('economy_class_capacity', models.IntegerField()),
                ('current_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_planes', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('delay', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=3)),
                ('column', models.CharField(max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('seat_class', models.CharField(choices=[('0', 'First Class'), ('1', 'Business Class'), ('2', 'Premium Class'), ('3', 'Economy Class')], default='4', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
        ),
    ]
