# Generated by Django 5.1.3 on 2024-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
