# Generated by Django 5.1.3 on 2024-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_name_alter_airport_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='plane',
            new_name='flight',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(choices=[('0', 'First Class'), ('1', 'Business Class'), ('2', 'Premium Class'), ('3', 'Economy Class')], default='4', max_length=20),
        ),
    ]
