# Generated by Django 5.1.4 on 2024-12-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_delay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='business_class_capacity',
            new_name='business_class_row_capacity',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='economy_class_capacity',
            new_name='economy_class_row_capacity',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='first_class_capacity',
            new_name='first_class_row_capacity',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='premium_class_capacity',
            new_name='premium_class_row_capacity',
        ),
    ]
