# Generated by Django 5.1.4 on 2024-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_business_class_row_capacity_plane_business_class_row_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(choices=[('0', 'First Class'), ('1', 'Business Class'), ('2', 'Premium Class'), ('3', 'Economy Class')], default='3', max_length=20),
        ),
    ]
