# Generated by Django 5.1.3 on 2024-12-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='announcements',
            field=models.ManyToManyField(related_name='announcements', to='posts.announcement'),
        ),
    ]
