# Generated by Django 5.1.4 on 2024-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Viet Nam', 'Viet Nam'), ('Lao', 'Lao'), ('China', 'China')], max_length=10),
        ),
    ]
